
version: '2.1'

services:

  backend:
    build: api
    env_file:
      - ./task_app.env
    links:
      - db:db
      - redis:redis
    volumes:
      - ./api/src/media:/app/media
      - ./api/src/static:/app/static
      - ./logs/backend:/var/log/task_app
    expose:
      - 8000
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.45

  celery_worker:
    build:
      context: api
    env_file:
      - ./task_app.env
    links:
      - redis:redis
    volumes:
      - ./api/src/media:/app/media
      - ./api/src/static:/app/static
      - ./logs/celery_worker:/var/log/balance_app
    depends_on:
      - redis
    restart: unless-stopped
    entrypoint: /app/celery_worker_entrypoint.sh
    networks:
      - balance_home_app_net
      
  celery_beat:
    build:
      context: api
    env_file:
      - ./task_app.env
    links:
      - redis:redis
    volumes:
      - ./api/src/media:/app/media
      - ./api/src/static:/app/static
      - ./logs/celery_beat:/var/log/balance_app
    depends_on:
      - redis
    restart: unless-stopped
    entrypoint: /app/celery_beat_entrypoint.sh
    networks:
      - balance_home_app_net

  redis:
    image: redis:7.0.7
    restart: unless-stopped
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.30

  db:
    image: postgres:15.1
    env_file:
      - ./postgres_db.env
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.20

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_containers
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./pgadmin.env
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.21

  nginx:
    build: nginx
    ports: 
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./api/src/static:/app/static
      - ./api/src/media:/app/media
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      balance_home_app_net:
        ipv4_address: 192.168.92.10

networks:
  balance_home_app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
