# Generated by Django 4.0.8 on 2022-11-26 17:46

import authentication.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='full name')),
                ('language', models.CharField(default='en', max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='language')),
                ('image', models.ImageField(default='users/default_user.jpg', upload_to=authentication.models._image_user_dir, verbose_name='profile image')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('code_sent', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='last code sent')),
                ('date_code_sent', models.DateTimeField(blank=True, null=True, verbose_name='date of last code sent')),
                ('pass_reset', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='last password reset code sent')),
                ('date_pass_reset', models.DateTimeField(blank=True, null=True, verbose_name='date of last password reset code sent')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', authentication.models.BalanceUserManager()),
            ],
        ),
    ]
