@startuml ClassDiagram

class User {
  id
  email
  full_name
  language
  image
  verified
  code_sent
  date_code_sent
  pass_reset
  date_pass_reset
}

class Task {
  id
  title
  description
  created
  finished
  deadline
  owner
}

note top of Task : If deadline has arrived and task has not finished, an email will be sent to owner's email.

User -> Task
@enduml